// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module4HW3.Data;

namespace Module4HW3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Module4HW3.Data.Entities.ClientEntity", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasMaxLength(50)
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClientId");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            DateOfBirth = new DateTimeOffset(new DateTime(1998, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Email = "ShamikaFJohnson@armyspy.com",
                            FirstName = "Shamika",
                            Gender = "F",
                            LastName = "Johnson",
                            PhoneNumber = "804-837-7518"
                        },
                        new
                        {
                            ClientId = 2,
                            Email = "JuanRHernandez@jourrapide.com",
                            FirstName = "Juan",
                            Gender = "M",
                            LastName = "Hernandez",
                            PhoneNumber = "916-663-8311"
                        },
                        new
                        {
                            ClientId = 3,
                            DateOfBirth = new DateTimeOffset(new DateTime(1975, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Email = "RichardMWilliamson@jourrapide.com",
                            FirstName = "Richard",
                            Gender = "M",
                            LastName = "Williamson",
                            PhoneNumber = "808-955-6175"
                        },
                        new
                        {
                            ClientId = 4,
                            Email = "MistyMFowler@armyspy.com",
                            FirstName = "Misty",
                            Gender = "F",
                            LastName = "Fowler",
                            PhoneNumber = "252-467-3244"
                        },
                        new
                        {
                            ClientId = 5,
                            Email = "SeanTJohnson@rhyta.com",
                            FirstName = "Sean",
                            Gender = "M",
                            LastName = "Johnson",
                            PhoneNumber = "540-605-5503"
                        });
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("HiredDate")
                        .HasMaxLength(7)
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("TitleId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.EmployeeProjectEntity", b =>
                {
                    b.Property<int>("EmployeeProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("money");

                    b.Property<DateTimeOffset>("StartedDate")
                        .HasMaxLength(7)
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeProjectId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProject");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.OfficeEntity", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OfficeId");

                    b.ToTable("Office");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Budget")
                        .HasColumnType("money");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("StartedDate")
                        .HasMaxLength(7)
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Budget = 5000m,
                            ClientId = 1,
                            Name = "ProjectOne",
                            StartedDate = new DateTimeOffset(new DateTime(2015, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            ProjectId = 2,
                            Budget = 15000m,
                            ClientId = 2,
                            Name = "ProjectTwo",
                            StartedDate = new DateTimeOffset(new DateTime(2013, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            ProjectId = 3,
                            Budget = 7500m,
                            ClientId = 3,
                            Name = "ProjectThree",
                            StartedDate = new DateTimeOffset(new DateTime(2019, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            ProjectId = 4,
                            Budget = 6000m,
                            ClientId = 4,
                            Name = "ProjectFour",
                            StartedDate = new DateTimeOffset(new DateTime(2019, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            ProjectId = 5,
                            Budget = 50000m,
                            ClientId = 5,
                            Name = "ProjectFive",
                            StartedDate = new DateTimeOffset(new DateTime(2010, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.TitleEntity", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TitleId");

                    b.ToTable("Title");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("Module4HW3.Data.Entities.OfficeEntity", "OfficeEntity")
                        .WithMany("EmployeeEntities")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module4HW3.Data.Entities.TitleEntity", "TitleEntity")
                        .WithMany("EmployeeEntities")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficeEntity");

                    b.Navigation("TitleEntity");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.EmployeeProjectEntity", b =>
                {
                    b.HasOne("Module4HW3.Data.Entities.EmployeeEntity", "EmployeeEntity")
                        .WithMany("EmployeeProjectEntities")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module4HW3.Data.Entities.ProjectEntity", "ProjectEntity")
                        .WithMany("EmployeeProjectEntities")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeEntity");

                    b.Navigation("ProjectEntity");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.ProjectEntity", b =>
                {
                    b.HasOne("Module4HW3.Data.Entities.ClientEntity", "ClientEntity")
                        .WithMany("ProjectEntities")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientEntity");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.ClientEntity", b =>
                {
                    b.Navigation("ProjectEntities");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.EmployeeEntity", b =>
                {
                    b.Navigation("EmployeeProjectEntities");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.OfficeEntity", b =>
                {
                    b.Navigation("EmployeeEntities");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.ProjectEntity", b =>
                {
                    b.Navigation("EmployeeProjectEntities");
                });

            modelBuilder.Entity("Module4HW3.Data.Entities.TitleEntity", b =>
                {
                    b.Navigation("EmployeeEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
